project:
  type: book
  output-dir: docs
  

book:
  title: "Workshop em R"
  author: "Felipe Madruga"
  search: true
  reader-mode: true
  sidebar: 
    style: floating
    border: false
  chapters: 
  - index.qmd
  - part: "PARTE 1"
    chapters:
      - capitulos/01.instalacao.qmd
      - capitulos/02.nocoes_iniciais.qmd
  - part: "PARTE 2"  
    chapters:
      - capitulos/03.colunas_linhas.qmd
      - capitulos/04.resumindo_dados.qmd
      - capitulos/05.adicionando_colunas.qmd
  - part: "PARTE 3"    
    chapters:
      - capitulos/06.importando_dados.qmd
#      - capitulos/07.unindo_base_de_dados.qmd
      - capitulos/09.handson.qmd
#  - part: "PARTE 4"
#    chapters:
#      - capitulos/10.graficos.qmd
#      - capitulos/11.tabelas.qmd
#      - capitulos/12.regressao.qmd
#     - capitulos/13.apis.qmd
#      - capitulos/14.vamos_pro_quarto.qmd
#      - capitulos/15.e_agora.qmd

bibliography: references.bib

format:
  html:
   lang: pt
   theme: litera
   link-external-newwindow: true
   code-overflow: wrap
   toc: true
   toc-title: "Índice do Conteúdo"
   cover-image: golden_cover.png
   reference-location: margin
   footnotes-hover: false
   lightbox: true
   fig-cap-location: top
   fig-align: center
   crossrefs-hover: false
  
  



