# Criando um Projeto e Importando Dados

**Isso aqui embaixo é provisório!**

Aqui devo mostrar a importância de organizar nosso trabalho com os dados em uma pasta própria ao utilizarmos a ferramenta de criação de projetos do RStudio, caso contrário toda vez que precisarmos carregar um arquivo teríamos que indicar o nome do caminho da pasta onde está esse arquivo. 

Nessa parte apresentar também diversos pacotes que podem ser utilizados para carregar dados, cada um deles para um tipo de extensão específica. Mencionar que é possível importar outros formatos, incluindo arquivos de outros programas, como por exemplo, stata. (deixar uma nota de rodapé indicando como fazer essa importação)

*Aqui também mencionar que quando estamos organizando uma pasta de trabalho, um maneira eficiente é criar pastas para dados brutos, dados processados, diferentes scritps de acordo com tarefas que são aplicadas nos dados, extração dos dados e limpeza, análise, criação de gráficos ou modelos, tudo isso indicados por números na frente do script/pasta para que fiquem melhor ordenados. (Se possível colocar uma imagem de uma pasta minha, ou criar uma como exemplo!)*

Nesta parte também mostrar como é possível criar nosso próprio banco de dados no R com a função `tibble()`, algo que será muito útil em várias situações. Indicar contudo, por meio de uma nota de rodapé que os *tibbles* são um tipo de `data.frame`, uma maneira comum também que os dados são armazenados no R, mas menos eficientes.


## Criando um Projeto no RStudio

Aqui vai ser a parte reservada para criação de um projeto para deixar os dados organizados.


## Importando Dados em **.csv**

Aqui mostrar quais funções são as responsáveis por importarmos os dados com essa extensão, e quais argumentos podemos utilizar dentro das funções.


## Importando Planilhas de Excel

Aqui mostrar que podemos carregar as planilhas do excel com o pacote `readxl`.


## Importando Planilhas do `googlesheets`

Mostrar o pacote que permite que possamos importar uma planilha na nuvem do google.

## Função `tibble()`

Mostrar como podemos em muitos casos construir uma pequena base de dados com essa função.

